sudo: required
language: generic
services:
  - docker

before-install:
  - docker build -t gkrish21/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gkrish21/docker-react npm run test